[package]
name = "kepler"
version = "1.0.0"
authors = ["Exein <engineering@exein.io>"]
edition = "2018"


[dependencies]
chrono = { version = "0.4.19", features = ["serde"] }
clap = "2.33.3"
cpe = "0.1.0"
diesel =  { version = "1.4.7", features = ["postgres", "r2d2"] }
dotenv = "0.15.0"
env_logger = "0.9.0"
flate2 = "1.0.21"
log = "0.4.14"
r2d2 = "0.8.9"
r2d2-diesel = "1.0.0"
regex = "1.5.4"
reqwest = { version = "0.11.4", features = ["blocking"] }
rocket = "0.4.10"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.67"
version-compare = "0.0.13"
lru = "0.6.6"
lazy_static = "1.4.0"
diesel_json = "0.1.1"

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["json"]
